package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

type AppInfo struct {
	Subdomain string
	Port      int
}

func Generate(dir string, scaffoldType string, app AppInfo) error {
	switch scaffoldType {
	case "docker":
		return generateDockerCompose(dir, app)
	case "systemd":
		return generateSystemd(dir, app)
	case "none":
		return nil
	default:
		return fmt.Errorf("unknown scaffold type %q (valid: docker, systemd, none)", scaffoldType)
	}
}

func generateDockerCompose(baseDir string, app AppInfo) error {
	content := fmt.Sprintf(`# Generated by Vitrina for %s
services:
  %s:
    build: .
    container_name: %s
    ports:
      - "127.0.0.1:%d:%d"
    environment:
      PORT: "%d"
    restart: unless-stopped
`, app.Subdomain, app.Subdomain, app.Subdomain, app.Port, app.Port, app.Port)

	return writeFile(baseDir, app.Subdomain, "docker-compose.yml", content)
}

func generateSystemd(baseDir string, app AppInfo) error {
	content := fmt.Sprintf(`# Generated by Vitrina for %s
[Unit]
Description=%s web application
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory=/opt/%s
ExecStart=/opt/%s/start.sh
Restart=on-failure
RestartSec=5
Environment=PORT=%d

[Install]
WantedBy=multi-user.target
`, app.Subdomain, app.Subdomain, app.Subdomain, app.Subdomain, app.Port)

	return writeFile(baseDir, app.Subdomain, fmt.Sprintf("%s.service", app.Subdomain), content)
}

func writeFile(baseDir, subdomain, filename, content string) error {
	dir := filepath.Join(baseDir, subdomain)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}
	path := filepath.Join(dir, filename)
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	fmt.Printf("  Generated boilerplate: %s\n", path)
	return nil
}
